# Generated by Django 5.0 on 2025-05-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualbalance',
            name='usdc_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
